# Generated by Django 5.2.7 on 2025-11-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado / En Preparación'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PAGADO', max_length=20),
        ),
    ]
