# Generated by Django 5.2.7 on 2025-11-24 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='Foto de Perfil')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono / WhatsApp')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección de Envío')),
                ('biografia', models.TextField(blank=True, help_text='Contanos un poco sobre vos y tu colección.', null=True, verbose_name='Biografía (Vendedor)')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
