# Generated by Django 5.2.7 on 2025-11-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, help_text='Contanos un poco sobre vos', null=True, verbose_name='Sobre mí'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de envío'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto'),
        ),
    ]
