"""
Django settings for tienda_artaud project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Intenta obtener la clave del entorno
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-1i2jpu6sd*#9@$d+j8%&bwbtl9&bp#b4z$ygxbyx36c!gtn2b5')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# Si existe la variable RENDER, desactivar DEBUG
DEBUG = 'RENDER' not in os.environ

# Permitir el dominio de Render
ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

APPS_PREINSTALADAS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

APPS_PROPIAS = [
    'productos',
    'usuarios',
    'carrito',
    'pedidos',
    'blog',
    'scraper',
]

APPS_TERCEROS = [
    'django.contrib.sites', # Para el 'allauth'
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

INSTALLED_APPS = APPS_PREINSTALADAS + APPS_PROPIAS + APPS_TERCEROS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoise para leer CSS online
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'tienda_artaud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'tienda_artaud', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'tienda_artaud.context_processors.navbar_data',
            ],
        },
    },
]

WSGI_APPLICATION = 'tienda_artaud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# (COMENTAR Y DESCOMENTAR CON LA OTRA)
# Configuración para escribir en la BB.DD online desde VSCode
# DATABASES = {
#     'default': dj_database_url.parse('DATABASE_URL')
# }

# Detectar si estamos en Render (o producción)
# (Asegúrate de que esta variable RENDER la definimos arriba con 'RENDER' in os.environ)
if 'RENDER' in os.environ:
    # --- CONFIGURACIÓN PARA RENDER (PostgreSQL) ---
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600
        )
    }
else:
    # --- CONFIGURACIÓN LOCAL (Tu SQLite de siempre) ---
    # Esto usa el método nativo de Django que no falla en Windows
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# # ???
# 'ENGINE': 'django.db.backends.postgresql'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ID del sitio (allauth)
SITE_ID = 1

# Configurar los 'backends' para permitir login con email/pass Y con Google
AUTHENTICATION_BACKENDS = [
    # Backend estándar de Django (login con usuario/contraseña)
    'django.contrib.auth.backends.ModelBackend',
    
    # Backend de Allauth (login con email y social logins)
    'allauth.account.auth_backends.AuthenticationBackend',
]


# ===============================================
# CONFIGURACIÓN DE LOGIN/LOGOUT
# ===============================================

# El usuario logueado (y deslogueado) va a la HOME.
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# URL para redirigir usuarios no autenticados cuando intentan acceder a una página restringida (@login_required)
# Dirige a la vista de login de Django
LOGIN_URL = 'account_login'

# Desactivar login por código para que siempre pida contraseña
ACCOUNT_LOGIN_BY_CODE_ENABLED = False

# Permite loguearse con usuario ó email
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'

# Campos que pide al registrarse
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_PASSWORD_REQUIRED = True

ACCOUNT_SIGNUP_FIELDS = ['email', 'username']

ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True

ACCOUNT_LOGIN_METHODS = {'username'}

ACCOUNT_SESSION_REMEMBER = True

# No requerir verificación de email por ahora (optional || none)
ACCOUNT_EMAIL_VERIFICATION = 'none'

# Evita la página intermedia de confirmación de "Sign In Via..."
SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '622197194026-esfheendbq8finld9lqd4kialbnboh36.apps.googleusercontent.com',
            'secret': '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',
        },
        'SCOPE': [
            'profile',
            'email',
        ],
    }
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Donde están todos los archivos 'static'
STATIC_URL = '/static/'

# Carpeta donde Django JUNTARÁ todo para producción (Destino)
# Render busca acá para servir los archivos.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Carpeta de Origen
# Debe estar SIEMPRE visible, fuera de cualquier if DEBUG.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Configuración de WhiteNoise para producción
# Solo activar la compresión y caché si no se está en modo DEBUG
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MERCADOPAGO_ACCESS_TOKEN = 'APP_USR-6973532859148559-112313-90998e1af493223f0045d212e8d8cf45-3008632151'


# =================================
# --- CONFIGURACIÓN PARA EMAILS ---
# =================================

# Imprime los correos en la terminal en lugar de intentar enviarlos por internet.
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Dirección de correo real para el sitio
EMAIL_HOST_USER = 'cristiangcabral@gmail.com' 

# La contraseña de aplicación (LA QUE SALE DE 'Seguridad' de GOOGLE)
# La leemos de las variables de entorno por seguridad
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

# Dirección predeterminada para los envíos automáticos
DEFAULT_FROM_EMAIL = 'Tienda Artaud <cristiangcabral@gmail.com>'