# Generated by Django 5.2.7 on 2025-10-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anio_lanzamiento', models.IntegerField()),
                ('formato', models.CharField(choices=[('VINILO', 'Vinilo'), ('CD', 'CD'), ('CASSETTE', 'Cassette')], max_length=10)),
                ('pais_origen', models.CharField(max_length=100)),
                ('condicion', models.CharField(choices=[('USADO', 'Usado'), ('NUEVO', 'Nuevo')], max_length=10)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=10)),
                ('descripcion', models.TextField(max_length=500)),
                ('edicion', models.CharField(blank=True, choices=[('ESTANDAR', 'Estándar'), ('ESPECIAL', 'Especial'), ('LIMITADA', 'Limitada')], default='ESTANDAR', max_length=10, null=True)),
                ('cantidad_discos', models.IntegerField(blank=True, null=True)),
                ('sello', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_canciones', models.IntegerField(blank=True, null=True)),
                ('genero_1', models.CharField(blank=True, choices=[('CLASICO', 'Clásico'), ('JAZZ', 'Jazz'), ('ROCK', 'Rock'), ('POP', 'Pop'), ('HIPHOP', 'Hip-hop'), ('ELECTRONICA', 'Electrónica'), ('FOLK', 'Folk')], max_length=50, null=True)),
                ('genero_2', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
