# Generated by Django 5.2.7 on 2025-10-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='titulo',
            new_name='album',
        ),
        migrations.AlterField(
            model_name='producto',
            name='formato',
            field=models.CharField(choices=[('VINILO', 'Vinilo'), ('CASSETTE', 'Cassette'), ('CD', 'CD')], max_length=10),
        ),
    ]
