# Generated by Django 5.2.7 on 2025-11-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_titulo_producto_album_alter_producto_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='formato',
            field=models.CharField(choices=[('VINILO', 'Vinilo'), ('CASSETTE', 'Cassette'), ('CD', 'CD'), ('VHS', 'VHS'), ('DVD', 'VHS'), ('BLURAY', 'Blu-ray')], max_length=10),
        ),
    ]
