# Generated by Django 5.2.7 on 2025-11-05 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_formato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='formato',
            field=models.CharField(choices=[('BLURAY', 'Blu-ray'), ('CASSETTE', 'Cassette'), ('CD', 'CD'), ('DVD', 'DVD'), ('VHS', 'VHS'), ('VINILO', 'Vinilo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero_1',
            field=models.CharField(blank=True, choices=[('CLASICO', 'Clásico'), ('ELECTRONICA', 'Electrónica'), ('FOLK', 'Folk'), ('HIPHOP', 'Hip-hop'), ('JAZZ', 'Jazz'), ('POP', 'Pop'), ('ROCK', 'Rock')], max_length=50, null=True),
        ),
    ]
