# Generated by Django 5.2.7 on 2025-11-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_vendedor_alter_producto_formato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
