# Generated by Django 5.2.7 on 2025-11-14 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='productos_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
