# Generated by Django 5.2.7 on 2025-11-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_producto_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero_1',
            field=models.CharField(blank=True, choices=[('CLASICO', 'Clásico'), ('ELECTRONICA', 'Electrónica'), ('FOLK', 'Folk'), ('HIPHOP', 'Hip-hop'), ('JAZZ', 'Jazz'), ('METAL', 'Metal'), ('POP', 'Pop'), ('RAP', 'Rap'), ('REGGAE', 'Reggae'), ('ROCK', 'Rock'), ('SOUNDTRACK', 'Soundtrack')], max_length=50, null=True),
        ),
    ]
