# Generated by Django 5.2.7 on 2025-11-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_genero_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado por Admin'),
        ),
    ]
