# Generated by Django 5.2.7 on 2025-11-23 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_aprobado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='pais_origen',
            new_name='pais',
        ),
    ]
