# Generated by Django 5.2.7 on 2025-11-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_rename_pais_origen_producto_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='album',
            field=models.CharField(max_length=200, verbose_name='Álbum'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='anio_lanzamiento',
            field=models.IntegerField(verbose_name='Año de lanzamiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_canciones',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de canciones'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_discos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de discos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='condicion',
            field=models.CharField(choices=[('USADO', 'Usado'), ('NUEVO', 'Nuevo')], max_length=10, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='edicion',
            field=models.CharField(blank=True, choices=[('ESTANDAR', 'Estándar'), ('ESPECIAL', 'Especial'), ('LIMITADA', 'Limitada')], default='ESTANDAR', max_length=10, null=True, verbose_name='Edición'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero_1',
            field=models.CharField(blank=True, choices=[('CLASICO', 'Clásico'), ('ELECTRONICA', 'Electrónica'), ('FOLK', 'Folk'), ('HIPHOP', 'Hip-hop'), ('JAZZ', 'Jazz'), ('METAL', 'Metal'), ('POP', 'Pop'), ('RAP', 'Rap'), ('REGGAE', 'Reggae'), ('ROCK', 'Rock'), ('SOUNDTRACK', 'Soundtrack')], max_length=50, null=True, verbose_name='Género principal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Género secundario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pais',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sello',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sello discográfico'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Copias disponibles'),
        ),
    ]
